import type { NewsSource } from './types.ts'

/** 固定一手来源；公开请求与管理员编辑均不能改变采集地址。 */
export const NEWS_SOURCES: NewsSource[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    url: 'https://openai.com/news/rss.xml',
    format: 'rss',
    hosts: ['openai.com'],
    toolIds: ['chatgpt'],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    url: 'https://www.anthropic.com/news',
    format: 'html',
    hosts: ['www.anthropic.com', 'anthropic.com'],
    toolIds: ['claude'],
    linkPattern: '/(?:news/|claude-(?:haiku|sonnet|opus))',
  },
  {
    id: 'google',
    name: 'Google AI',
    url: 'https://blog.google/products-and-platforms/products/gemini/rss/',
    format: 'rss',
    hosts: ['blog.google'],
    toolIds: ['gemini', 'notebooklm'],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    url: 'https://www.deepseek.com/news/',
    format: 'html',
    hosts: ['www.deepseek.com', 'deepseek.com'],
    toolIds: ['deepseek'],
    linkPattern: '/(?:en/)?news/',
  },
  {
    id: 'qwen',
    name: 'Qwen',
    url: 'https://qwen.ai/api/v2/article/retrieval?type=qwen_ai&language=zh-CN',
    format: 'qwen',
    hosts: ['qwen.ai'],
    toolIds: ['qwen'],
  },
  {
    id: 'copilot',
    name: 'GitHub Copilot',
    url: 'https://github.blog/changelog/label/copilot/feed/',
    format: 'rss',
    hosts: ['github.blog'],
    toolIds: ['copilot'],
  },
  {
    id: 'cursor',
    name: 'Cursor',
    url: 'https://cursor.com/changelog',
    format: 'html',
    hosts: ['cursor.com', 'www.cursor.com'],
    toolIds: ['cursor'],
    linkPattern: '/changelog/',
  },
  {
    id: 'ollama',
    name: 'Ollama',
    url: 'https://api.github.com/repos/ollama/ollama/releases?per_page=8',
    format: 'github',
    hosts: ['api.github.com', 'github.com'],
    toolIds: ['ollama'],
  },
  {
    id: 'kimi',
    name: 'Kimi',
    url: 'https://www.kimi.com/news',
    format: 'html',
    hosts: ['www.kimi.com', 'kimi.com'],
    toolIds: ['kimi'],
    linkPattern: '/news/',
  },
]

export const NEWS_TOOL_NAMES: Record<string, string> = {
  chatgpt: 'ChatGPT',
  claude: 'Claude',
  gemini: 'Gemini',
  notebooklm: 'NotebookLM',
  deepseek: 'DeepSeek',
  qwen: '通义千问',
  copilot: 'GitHub Copilot',
  cursor: 'Cursor',
  ollama: 'Ollama',
  kimi: 'Kimi',
}
